name: check
on: push

jobs:
  check:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            path_to_exe: ./build/Debug/RangeShifter.exe
          - os: ubuntu-latest
            path_to_exe: ./build/RangeShifter
          - os: macos-latest
            path_to_exe: ./build/RangeShifter
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - if: ${{ matrix.path_to_exe }}
        run: npm install -g npm@${{ matrix.path_to_exe }}
      - run: npm --version
