name: check
on: push

jobs:
  check:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: g++ -o ./run_on_gha/rs_test_project/rs.exe ./src/*.cpp ./src/RScore/*.cpp -DRSDEBUG -DLINUX_CLUSTER -DRSWIN64

      - name: run
        run: |
          cd ./run_on_gha/rs_test_project
          ./rs.exe

      - name: check_output
        run: |
          cd ./run_on_gha/rs_test_project 
          rm Outputs/DebugLog.txt
          bash check_output.bash
        # DebugLog contains addresses, changes every run

          
